site_name: Protocoles Labo anatomie Tours

repo_url: https://github.com/destrieux/labdoc
//edit_uri: https://lab.civicrm.org/extensions/yourproject_LANGUAGE/-/edit/master
site_description: 'Documentation Labo anatomie Tours.'
site_author: 'Christophe Destrieux'
theme:
  name:
    material

//nav:
//- Home: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: fr

nav:
  - Ex vivo imaging: 
    - 'Ex vivo surface recon ': 'Exvivo/Reconstruction/reconstruction.md'
  - Photogrammetry:
    - 'From metashape to SKN3D': 'Photogrammetry/From_metashape_to_SKN3D.md'
